version: '2'

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rfid
      MYSQL_USER: rfid
      MYSQL_PASSWORD: rfid
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'