version: '3.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: rfid
      MYSQL_USER: rfid
      MYSQL_PASSWORD: rfid
      MYSQL_ROOT_PASSWORD: 'yes'

volumes:
  mysql_data:
